package net.es.oscars.dto.pss;

public enum EthPipeType {
    REQUESTED,
    JUNOS_SWITCH_TO_JUNOS_SWITCH,
    JUNOS_SWITCH_TO_ALU_VPLS,
    ALU_VPLS_TO_JUNOS_SWITCH,
    JUNOS_SWITCH_TO_JUNOS_VPLS,
    JUNOS_VPLS_TO_JUNOS_SWITCH
}
