package net.es.oscars.topo.pop;

public enum ConsistencyError {
    DEVICE_HAS_NO_POSITION,
    POSITION_HAS_NO_DEVICE,
    DEVICE_HAS_NO_ADDRESS,
    MPLS_IFCE_HAS_NO_ADDRESS,
    ADDRESS_URN_NOT_FOUND,
    MISSING_INVERSE_ADJCY,
    MISMATCHED_INVERSE_ADJCY,
    MISSING_INTERNAL_ADJCY,


}
